# Generated by Django 2.0 on 2018-02-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_view_zoo_stays_with_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaysWithEndDate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('animal_name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'zoo_stays_with_end',
            },
        ),
    ]
